spring:
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    kr.inventory: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.boot.autoconfigure: INFO
    jdk.internal.httpclient: INFO

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000